# 03 - Portfolio Construction Engine

Goal: recommend transparent portfolios for conservative, balanced, and aggressive investor profiles.

In [1]:
from pathlib import Path
import sys

ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
sys.path.append(str(ROOT / 'src'))

import pandas as pd
import plotly.express as px

from invest_intel.data import build_returns_matrix, load_prices
from invest_intel.portfolio import construct_profile_portfolio, random_portfolios

In [2]:
prices = load_prices()
recent_prices = prices[prices['date'] >= '2015-01-01']
returns = build_returns_matrix(recent_prices, min_obs=252).dropna(how='all')
returns.shape

(1565, 49)

In [3]:
profile_outputs = {}
for profile in ['conservative', 'balanced', 'aggressive']:
    weights, metrics, selected = construct_profile_portfolio(returns, profile=profile)
    profile_outputs[profile] = {'weights': weights, 'metrics': metrics, 'selected': selected}
    print(profile, metrics)
    display(selected[['symbol', 'weight', 'expected_return', 'annualized_volatility', 'sharpe_score']])

conservative {'annualized_return': 0.24448617945715712, 'annualized_volatility': 0.20227413088020696, 'sharpe_ratio': 0.9120601762289394, 'sortino_ratio': np.float64(1.1455096998378371), 'max_drawdown': -0.35983343850956606, 'var_95': -0.017018135496155374, 'expected_shortfall_95': -0.028864508524897855}

        symbol    weight  expected_return  annualized_volatility  sharpe_score
20  HINDUNILVR  0.100000         0.210355               0.237602      0.632802
1   ASIANPAINT  0.100000         0.231845               0.265990      0.646059
31   NESTLEIND  0.100000         0.185074               0.255114      0.490267
44  ULTRACEMCO  0.097054         0.180835               0.292208      0.413523
37    SHREECEM  0.090628         0.224431               0.312928      0.525460
43       TITAN  0.086338         0.273775               0.328475      0.650811
35    RELIANCE  0.078051         0.207346               0.363351      0.405519
4   BAJAJFINSV  0.077911         0.413492               0.364003      0.971125
0   ADANIPORTS  0.077048         0.201129               0.368081      0.383417
40   TATASTEEL  0.072589         0.227428               0.390693      0.428542
19    HINDALCO  0.067953         0.221177               0.417344      0.386196
5   BAJFINANCE  0.052427         0.376387               0.540944      0.584880

balanced {'annualized_return': 0.27085487236357286, 'annualized_volatility': 0.21139753286188556, 'sharpe_ratio': 0.9974329856599261, 'sortino_ratio': np.float64(1.2237752596282678), 'max_drawdown': -0.38199275485774087, 'var_95': -0.01776298983501845, 'expected_shortfall_95': -0.030256774849530647}

        symbol    weight  expected_return  annualized_volatility  sharpe_score
4   BAJAJFINSV  0.148977         0.413492               0.364003      0.971125
43       TITAN  0.099839         0.273775               0.328475      0.650811
1   ASIANPAINT  0.099110         0.231845               0.265990      0.646059
20  HINDUNILVR  0.097076         0.210355               0.237602      0.632802
5   BAJFINANCE  0.089725         0.376387               0.540944      0.584880
37    SHREECEM  0.080609         0.224431               0.312928      0.525460
31   NESTLEIND  0.075210         0.185074               0.255114      0.490267
40   TATASTEEL  0.065741         0.227428               0.390693      0.428542
44  ULTRACEMCO  0.063437         0.180835               0.292208      0.413523
35    RELIANCE  0.062210         0.207346               0.363351      0.405519
19    HINDALCO  0.059245         0.221177               0.417344      0.386196
0   ADANIPORTS  0.058819         0.201129               0.368081      0.383417

aggressive {'annualized_return': 0.28255510935577544, 'annualized_volatility': 0.21413444741225207, 'sharpe_ratio': 1.0393241818179393, 'sortino_ratio': np.float64(1.2767142707253059), 'max_drawdown': -0.38659607100837456, 'var_95': -0.01764162009956506, 'expected_shortfall_95': -0.030520762821821004}

        symbol    weight  expected_return  annualized_volatility  sharpe_score
4   BAJAJFINSV  0.193010         0.413492               0.364003      0.971125
43       TITAN  0.105889         0.273775               0.328475      0.650811
1   ASIANPAINT  0.104731         0.231845               0.265990      0.646059
20  HINDUNILVR  0.101524         0.210355               0.237602      0.632802
5   BAJFINANCE  0.090213         0.376387               0.540944      0.584880
37    SHREECEM  0.076821         0.224431               0.312928      0.525460
31   NESTLEIND  0.069234         0.185074               0.255114      0.490267
40   TATASTEEL  0.056579         0.227428               0.390693      0.428542
44  ULTRACEMCO  0.053631         0.180835               0.292208      0.413523
35    RELIANCE  0.052082         0.207346               0.363351      0.405519
19    HINDALCO  0.048404         0.221177               0.417344      0.386196
0   ADANIPORTS  0.047882         0.201129               0.368081      0.383417

In [4]:
balanced = profile_outputs['balanced']['selected']
px.bar(balanced, x='symbol', y='weight', title='Balanced profile allocation')

In [5]:
frontier = random_portfolios(returns.dropna(), n_portfolios=1000)
px.scatter(frontier, x='annualized_volatility', y='expected_return', color='sharpe_ratio', title='Random portfolio frontier')